[package]
name = "file_sync_client"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
brotli = "3.3.4"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
reqwest = { version = "0.11", features = ["multipart", "stream", "json", "brotli", "gzip", "blocking", "tokio-runtime", "json", "rustls-tls"] }
tokio-util = { version = "0.7", features = ["io"] }
