[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
tar = "0.4"
flate2 = "1"
reqwest = { version = "0.11", features = ["blocking", "multipart"] }
anyhow = "1"
